### ISSUE TITLE
Responsive Menu

### ISSUE THREAD

**Issue by joshgonzales** [vantagedesign/ace-documentation#16]
responsive menu is not working for me:

https://antiracism-canada.netlify.app/
https://github.com/joshgonzales/bitly_antiracism_canada

**Comment by julianflapper** [comment]
Hi,

Your javascript libraries aren't being loaded properly.

Their source is set to:
"‘https://antiracism-canada.netlify.applib/jquery.min.js’"
Notice the missing "/" between ".app" and "lib"?

This might be fixed by adding a "/" to your site's URL in your config.toml.
Otherwise, consider changing the script's src in "theme/ace-documentation/layouts/footer.html"
