### ISSUE TITLE
next-prev-page has unexpected behavior with last page

### ISSUE THREAD

**Issue by jhollowe** [vantagedesign/ace-documentation#5]
When on the last page of the site ([example from demo site](https://docs.vantage-design.com/ace/shortcodes/panel/)), the navigation footer's "next" link exists and points to the first element of its section. When using nested sections, it displays the first page of the *root* section.

#### Example of nested:
layout: (single letter pages are _index.md and double letters are standard pages
![layout](https://user-images.githubusercontent.com/2881268/80999663-07868280-8e13-11ea-950d-6e715c77a12c.png)

footer on page BB:
![footer on page BB](https://user-images.githubusercontent.com/2881268/80999605-ef166800-8e12-11ea-947d-0471159927d6.png)

**Comment by julianflapper** [comment]
@jhollowe Thanks for reporting this.
I will look into it showing no "next" when it's the very last page. Though, the behavior may not be so unwanted since it allso makes it possible to go to the next section when at the end of a current section. 

In your example, when at page B, it properly displays BB as next, and AA as previous. So that behavior is correct, but I agree that it shouldn't loop back around to AA when at page BB.

**Comment by julianflapper** [comment]
I'm going to leave this as-is, since in my opinion it is not a very disturbing behavior and may actually be useful when supporting users in browsing the documentation.
